# Site settings
title: "ODS: Data Science School, 2015"
email: 
description: > # this means to ignore newlines until "baseurl:"
  Data Science School at DeKUT in Nyeri, Kenya.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://gpss.cc" # the base hostname & protocol for your site
twitter_username: datascienceshef
github_username:  SheffieldML
facebook_page: gaussianprocesssummerschool

youtube:
  height: 315
  width: 560

conference:
  hosts:
  - {name: Ciira wa Maina, url: "https://sites.google.com/site/cwamainadekut/"}
  organizers:
  - {name: Neil Lawrence, url: "http://inverseprobability.com"}
  - {name: Andreas Damianou, url: "http://staffwww.dcs.sheffield.ac.uk/people/A.Damianou/index.html"}
  - {name: John Quinn, url: "http://air.ug/~jquinn/"}
  name: Data Science School
  hosturl: https://sites.google.com/site/dekutdatascienceworkshop2015/
  location: Dedan Kimathi University of Technlogy, Nyeri, Kenya
  year: 2015
  month: June
  dates:
  - {date: 15, day: Monday, month: June, year: 2015}
  - {date: 16, day: Tuesday, month: June, year: 2015}
  - {date: 17, day: Wednesday, month: June, year: 2015}
  
# Build settings
markdown: kramdown

